version: '3'
services:
  app:
    build: ./images
    command: ["go", "run", "main.go"]
    container_name: goweb
    hostname: goweb
    volumes:
      - ../:/go/src/app
    ports:
      - "8080:8080"
    links: 
      - db
    depends_on: 
      - db      
  db:
    image: postgres
    hostname: postgres
    container_name: gopostgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: dev_pass
    ports:
      - 5432:5432  